# Generated by Django 2.2.6 on 2019-12-02 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('context', models.TextField(default='', max_length=200)),
                ('season', models.IntegerField(blank=True, default=0, null=True, verbose_name='season')),
            ],
        ),
        migrations.CreateModel(
            name='ClassWinRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.CharField(default='', max_length=100)),
                ('win', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('lose', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('rate', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('total', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('season', models.IntegerField(blank=True, default=0, null=True, verbose_name='season')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField(verbose_name='date published')),
                ('match_table_release', models.BooleanField(default=False, verbose_name='マッチング表の公表')),
                ('register_release', models.BooleanField(default=False, verbose_name='登録ページの公表')),
                ('season', models.IntegerField(blank=True, default=0, null=True, verbose_name='season')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('win', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('lose', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('e_win', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('e_lose', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('nm_win', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('nm_lose', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('d_win', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('d_lose', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('b_win', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('b_lose', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('r_win', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('r_lose', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('v_win', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('v_lose', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('w_win', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('w_lose', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('nc_win', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('nc_lose', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('season', models.IntegerField(blank=True, default=0, null=True, verbose_name='season')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(blank=True, default=0, null=True, verbose_name='season')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('point', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('grosspoint', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('season', models.IntegerField(blank=True, default=0, null=True, verbose_name='season')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(default='-', max_length=100)),
                ('team2', models.CharField(default='-', max_length=100)),
                ('team3', models.CharField(default='-', max_length=100)),
                ('team4', models.CharField(default='-', max_length=100)),
                ('team5', models.CharField(default='-', max_length=100)),
                ('team6', models.CharField(default='-', max_length=100)),
                ('team7', models.CharField(default='-', max_length=100)),
                ('team8', models.CharField(default='-', max_length=100)),
                ('quauter1', models.CharField(default='-', max_length=100)),
                ('quauter2', models.CharField(default='-', max_length=100)),
                ('quauter3', models.CharField(default='-', max_length=100)),
                ('quauter4', models.CharField(default='-', max_length=100)),
                ('semi1', models.CharField(default='-', max_length=100)),
                ('semi2', models.CharField(default='-', max_length=100)),
                ('winner', models.CharField(default='-', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(default='', max_length=100)),
                ('point', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(blank=True, default=0, null=True, verbose_name='season')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Match')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='attendance.Team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='attendance.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Reported',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(default='', max_length=100)),
                ('first', models.CharField(default='', max_length=100)),
                ('second', models.CharField(default='', max_length=100)),
                ('third', models.CharField(default='', max_length=100)),
                ('fourth', models.CharField(default='', max_length=100)),
                ('fifth', models.CharField(default='', max_length=100)),
                ('firstl', models.CharField(default='', max_length=100)),
                ('secondl', models.CharField(default='', max_length=100)),
                ('thirdl', models.CharField(default='', max_length=100)),
                ('fourthl', models.CharField(default='', max_length=100)),
                ('fifthl', models.CharField(default='', max_length=100)),
                ('firstwl', models.CharField(default='', max_length=100)),
                ('secondwl', models.CharField(default='', max_length=100)),
                ('thirdwl', models.CharField(default='', max_length=100)),
                ('fourthwl', models.CharField(default='', max_length=100)),
                ('fifthwl', models.CharField(default='', max_length=100)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(default='', max_length=100)),
                ('first', models.CharField(default='', max_length=100)),
                ('second', models.CharField(default='', max_length=100)),
                ('third', models.CharField(default='', max_length=100)),
                ('fourth', models.CharField(default='', max_length=100)),
                ('fifth', models.CharField(default='', max_length=100)),
                ('hoketsu', models.CharField(default='', max_length=100)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Match')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.CharField(default='', max_length=100)),
                ('wl', models.CharField(default='', max_length=100)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Team'),
        ),
    ]
