# Generated by Django 2.2.6 on 2019-12-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='season',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='season'),
        ),
    ]
