# Generated by Django 2.2.6 on 2020-03-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='start',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='words',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='context',
            field=models.TextField(default='', max_length=500),
        ),
    ]
