# Generated by Django 2.2.6 on 2020-03-31 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20200331_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='start',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='words',
            field=models.TextField(default='', max_length=500, null=True),
        ),
    ]
