# Generated by Django 2.2.6 on 2019-12-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_past'),
    ]

    operations = [
        migrations.AddField(
            model_name='past',
            name='season',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='season'),
        ),
    ]
