# Generated by Django 2.2.6 on 2020-03-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20200331_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='past',
            name='place1',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='past',
            name='place10',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='past',
            name='place2',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='past',
            name='place3',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='past',
            name='place4',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='past',
            name='place5',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='past',
            name='place6',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='past',
            name='place7',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='past',
            name='place8',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='past',
            name='place9',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
