# Generated by Django 2.2.6 on 2020-01-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_past_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='penalty',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
    ]
