# Generated by Django 2.2.6 on 2020-01-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_team_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='gp',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='season'),
        ),
        migrations.AlterField(
            model_name='player',
            name='lose',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='lose'),
        ),
        migrations.AlterField(
            model_name='player',
            name='win',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='win'),
        ),
        migrations.AlterField(
            model_name='team',
            name='grosspoint',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='得点差(ペナルティ除く)'),
        ),
        migrations.AlterField(
            model_name='team',
            name='penalty',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ペナルティ(正の数でつけてください)'),
        ),
        migrations.AlterField(
            model_name='team',
            name='point',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='勝ち点'),
        ),
    ]
