# Generated by Django 2.2.6 on 2020-03-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_other_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='other_tournament',
            name='Rank',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
