# Generated by Django 2.2.6 on 2020-03-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_other_tournament_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_tournament',
            name='prize',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='prize'),
        ),
    ]
