# Generated by Django 2.2.6 on 2020-01-04 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20200103_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='regist_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='team',
            name='gp',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='得点差-ペナルティ'),
        ),
    ]
