# Generated by Django 2.2.6 on 2019-10-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='context',
            field=models.TextField(default='', max_length=200),
        ),
    ]
