# Generated by Django 2.2.6 on 2019-10-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_auto_20191007_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='Registerd',
        ),
        migrations.AddField(
            model_name='blog',
            name='season',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='classwinrate',
            name='season',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='season',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='table',
            name='season',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='team',
            name='season',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
    ]
